version: "3.8"

services:
  redis:
    image: redis:alpine3.22
    container_name: redis-server
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    command:
      redis-server --appendonly yes
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: zhangxiao
      MYSQL_DATABASE: day21
      MYSQL_USER: zhangxiao
      MYSQL_PASSWORD: zhangxiao
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/mysql.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
